apiVersion: v1
kind: ConfigMap
metadata:
  name: temporal-web-config
  namespace: temporal
data:
  docker.yaml: |-
    # enable-template
    temporalGrpcAddress: {{ env "TEMPORAL_ADDRESS" | default "127.0.0.1:7233" }}
    port: {{ env "TEMPORAL_UI_PORT" | default "8080" }}
    publicPath: {{ env "TEMPORAL_UI_PUBLIC_PATH" | default "" }}
    enableUi: {{ env "TEMPORAL_UI_ENABLED" | default "true" }}
    defaultNamespace: {{ env "TEMPORAL_DEFAULT_NAMESPACE" | default "default" }}
    tls:
      caFile: {{ env "TEMPORAL_TLS_CA" | default "" }}
      certFile: {{ env "TEMPORAL_TLS_CERT" | default "" }}
      keyFile: {{ env "TEMPORAL_TLS_KEY" | default "" }}
      caData: {{ env "TEMPORAL_TLS_CA_DATA" | default "" }}
      certData: {{ env "TEMPORAL_TLS_CERT_DATA" | default "" }}
      keyData: {{ env "TEMPORAL_TLS_KEY_DATA" | default "" }}
      enableHostVerification: {{ env "TEMPORAL_TLS_ENABLE_HOST_VERIFICATION" | default "false" }}
      serverName: {{ env "TEMPORAL_TLS_SERVER_NAME" | default "" }}
    auth:
      enabled: {{ env "TEMPORAL_AUTH_ENABLED" | default "false" }}
      providers:
        - label: {{ env "TEMPORAL_AUTH_LABEL" | default "sso" }}
          type: {{ env "TEMPORAL_AUTH_TYPE" | default "oidc" }}
          providerUrl: {{ env "TEMPORAL_AUTH_PROVIDER_URL" }}
          issuerUrl: {{ env "TEMPORAL_AUTH_ISSUER_URL" | default "" }}
          clientId: {{ env "TEMPORAL_AUTH_CLIENT_ID" }}
          clientSecret: {{ env "TEMPORAL_AUTH_CLIENT_SECRET" }}
          callbackUrl: {{ env "TEMPORAL_AUTH_CALLBACK_URL" }}
          scopes:
          {{- if env "TEMPORAL_AUTH_SCOPES" }}
          {{- range env "TEMPORAL_AUTH_SCOPES" | split "," }}
            - {{ . }}
          {{- end }}
          {{- end }}
          options:
            audience: E1Id4VSoAEDoZnMB1ykNyyvwlSaGUeZe
    codec:
      endpoint: {{ env "TEMPORAL_CODEC_ENDPOINT" | default "" }}
      passAccessToken: {{ env "TEMPORAL_CODEC_PASS_ACCESS_TOKEN" | default "false" }}
      includeCredentials: {{ env "TEMPORAL_CODEC_INCLUDE_CREDENTIALS" | default "false" }}
