apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: auth
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Auth
  sourceRepos:
  - '*'
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*''