apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-secrets
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: oci-secret-store
    kind: ClusterSecretStore
  target:
    name: github-secrets
  data:
    - secretKey: CLIENT_SECRET
      remoteRef:
        key: argocd_github_client_secret