apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-secrets
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: oci-secret-store
    kind: ClusterSecretStore
  target:
    name: github-secrets
  data:
    - secretKey: CLIENT_SECRET
      remoteRef:
        key: kargo_github_app_client_secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gar-portfolio-docker-repository
  namespace: kargo-shared-resources
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: kubernetes-secret-store
    kind: ClusterSecretStore
  target:
    name: gar-portfolio-docker-repository
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          kargo.akuity.io/cred-type: image
      data:
        repoURL: ^europe-west2-docker\.pkg\.dev/portfolio-463406/docker-repository/.*$
        repoURLIsRegex: "true"
        username: oauth2accesstoken
        password: '{{- $config := fromJson (index . ".dockerconfigjson") -}}{{- $auth := index $config.auths "https://europe-west2-docker.pkg.dev" -}}{{- $auth.password -}}'
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: gcp-pull-secret
        property: .dockerconfigjson
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kargo-portfolio-git-rw
  namespace: kargo-shared-resources
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: oci-secret-store
    kind: ClusterSecretStore
  target:
    name: kargo-portfolio-git-rw
    creationPolicy: Owner
    template:
      metadata:
        labels:
          kargo.akuity.io/cred-type: git
      data:
        repoURL: ^https://github.com/abayleypublic/.*$
        repoURLIsRegex: "true"
        githubAppClientID: Iv23li0arvb7L4qz9fwL
        githubAppInstallationID: 145296641
        githubAppPrivateKey: "{{ .githubAppPrivateKey }}"
  data:
    - secretKey: githubAppPrivateKey
      remoteRef:
        key: kargo_github_app_private_key