apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: roam
spec:
  subscriptions:
  - image:
      repoURL: europe-west2-docker.pkg.dev/portfolio-463406/docker-repository/activity_tracker_charity
      imageSelectionStrategy: NewestBuild