apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-roam
  namespace: argocd
spec:
  project: activity
  source:
    repoURL: https://github.com/abayleypublic/activity_tracker_charity
    targetRevision: v1.1.16
    path: deploy/overlays/prod
    kustomize:
      images:
        - name: europe-west2-docker.pkg.dev/portfolio-463406/docker-repository/activity_tracker_charity
          newTag: v1.1.16
  destination:
    name: portfolio
    namespace: prod-roam
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    automated:
      selfHeal: true
      prune: true
