apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: temporal
  namespace: argocd
spec:
  project: system
  sources:
    - repoURL: https://github.com/abayleypublic/apps
      targetRevision: HEAD
      path: deploy/system/temporal/chart
      helm:
        valueFiles:
          - ../values.yaml
    - repoURL: https://github.com/abayleypublic/apps
      targetRevision: HEAD
      path: deploy/system/temporal/base
    - repoURL: https://github.com/abayleypublic/temporal_codec
      targetRevision: v0.0.3
      path: deploy/overlays/prod
      kustomize:
        images:
          - codec=europe-west2-docker.pkg.dev/portfolio-463406/docker-repository/temporal-codec:v0.0.3
  destination:
    name: portfolio
    namespace: temporal
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    automated:
      selfHeal: true
      prune: true