image:
  tag: v1.10.8

api:
  argocd:
    urls:
      "": "https://argocd.austinbayley.co.uk"
  
  ingress:
    enabled: false

  tls:
    enabled: false
    terminatedUpstream: true

  adminAccount:
    enabled: false

  host: "kargo.austinbayley.co.uk"

  oidc:
    enabled: true

    admins:
      claims:
        groups:
          - "abayleyportfolio"

    dex:
      enabled: true
      connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: Iv23lidURGmEy1jsqZ1z
            clientSecret: "$CLIENT_SECRET"
            redirectURI: https://kargo.austinbayley.co.uk/dex/callback
            loadAllGroups: true
            teamNameField: slug
      envFrom:
       - secretRef:
           name: github-secrets

controller:
  env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /etc/workload-identity/credential-configuration.json

  volumeMounts:
    - name: token
      mountPath: /var/run/service-account
      readOnly: true
    - name: workload-identity
      mountPath: /etc/workload-identity
      readOnly: true

  volumes:
    - name: workload-identity
      configMap:
        name: workload-identity
    - name: token
      projected:
        sources:
          - serviceAccountToken:
             audience: "https://kargo.austinbayley.co.uk"
             path: "token"
             expirationSeconds: 3600