image:
  tag: v1.10.8

api:
  argocd:
    urls:
      "": "https://argocd.austinbayley.co.uk"
  
  ingress:
    enabled: false

  tls:
    enabled: false
    terminatedUpstream: true

  adminAccount:
    enabled: false

  host: "kargo.austinbayley.co.uk"

  oidc:
    enabled: true

    admins:
      claims:
        groups:
          - "abayleyportfolio"

    dex:
      enabled: true
      connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: Iv23lidURGmEy1jsqZ1z
            clientSecret: "$CLIENT_SECRET"
            redirectURI: https://kargo.austinbayley.co.uk/dex/callback
            loadAllGroups: true
            teamNameField: slug
      envFrom:
       - secretRef:
           name: github-secrets
