apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stg-queue
  namespace: argocd
spec:
  project: queue
  source:
    repoURL: https://github.com/abayleypublic/queue
    targetRevision: v1.2.5
    path: deploy/overlays/stg
    kustomize:
      images:
        - name: europe-west2-docker.pkg.dev/portfolio-463406/docker-repository/queue_backend
          newTag: v1.2.5
        - name: europe-west2-docker.pkg.dev/portfolio-463406/docker-repository/queue_gateway
          newTag: v1.2.5
        - name: europe-west2-docker.pkg.dev/portfolio-463406/docker-repository/queue_mcp
          newTag: v1.2.5
        - name: europe-west2-docker.pkg.dev/portfolio-463406/docker-repository/queue_service
          newTag: v1.2.5
        - name: europe-west2-docker.pkg.dev/portfolio-463406/docker-repository/queue_ui
          newTag: v1.2.5
  destination:
    name: portfolio
    namespace: stg-queue
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    automated:
      selfHeal: true
      prune: true
