apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  annotations:
    kargo.akuity.io/color: amber
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: queue
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - uses: set-metadata
        config:
          updates:
          - kind: Stage
            name: staging
            values:
              promotion-actor: ${{ ctx.meta.promotion.actor }}
      - task:
          name: apps-promotion
          kind: ClusterPromotionTask
        vars:
        - name: path
          value: deploy/apps/queue/stg
        - name: targetRevision
          value: ${{ imageFrom('europe-west2-docker.pkg.dev/portfolio-463406/docker-repository/queue_backend').Tag }}
        - name: images
          value: >-
            ["europe-west2-docker.pkg.dev/portfolio-463406/docker-repository/queue_backend:${{ imageFrom('europe-west2-docker.pkg.dev/portfolio-463406/docker-repository/queue_backend').Tag }}",
            "europe-west2-docker.pkg.dev/portfolio-463406/docker-repository/queue_gateway:${{ imageFrom('europe-west2-docker.pkg.dev/portfolio-463406/docker-repository/queue_backend').Tag }}",
            "europe-west2-docker.pkg.dev/portfolio-463406/docker-repository/queue_mcp:${{ imageFrom('europe-west2-docker.pkg.dev/portfolio-463406/docker-repository/queue_backend').Tag }}",
            "europe-west2-docker.pkg.dev/portfolio-463406/docker-repository/queue_service:${{ imageFrom('europe-west2-docker.pkg.dev/portfolio-463406/docker-repository/queue_backend').Tag }}",
            "europe-west2-docker.pkg.dev/portfolio-463406/docker-repository/queue_ui:${{ imageFrom('europe-west2-docker.pkg.dev/portfolio-463406/docker-repository/queue_backend').Tag }}"]
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  annotations:
    kargo.akuity.io/color: violet
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: queue
    sources:
      stages:
      - staging
  promotionTemplate:
    spec:
      steps:
      - task:
          name: apps-promotion
          kind: ClusterPromotionTask
        vars:
        - name: path
          value: deploy/apps/queue/prod
        - name: targetRevision
          value: ${{ imageFrom('europe-west2-docker.pkg.dev/portfolio-463406/docker-repository/queue_backend').Tag }}
        - name: images
          value: >-
            ["europe-west2-docker.pkg.dev/portfolio-463406/docker-repository/queue_backend:${{ imageFrom('europe-west2-docker.pkg.dev/portfolio-463406/docker-repository/queue_backend').Tag }}",
            "europe-west2-docker.pkg.dev/portfolio-463406/docker-repository/queue_gateway:${{ imageFrom('europe-west2-docker.pkg.dev/portfolio-463406/docker-repository/queue_backend').Tag }}",
            "europe-west2-docker.pkg.dev/portfolio-463406/docker-repository/queue_mcp:${{ imageFrom('europe-west2-docker.pkg.dev/portfolio-463406/docker-repository/queue_backend').Tag }}",
            "europe-west2-docker.pkg.dev/portfolio-463406/docker-repository/queue_service:${{ imageFrom('europe-west2-docker.pkg.dev/portfolio-463406/docker-repository/queue_backend').Tag }}",
            "europe-west2-docker.pkg.dev/portfolio-463406/docker-repository/queue_ui:${{ imageFrom('europe-west2-docker.pkg.dev/portfolio-463406/docker-repository/queue_backend').Tag }}"]
        - name: openpr
          value: "true"